
CREATE PROC [dbo].[usp_MP_JOB_HISTORY]
@PERSON_ID INT
AS
SELECT DISTINCT
	M.PERSON_ID,
	MC.EMPLOYER_ID,
	EMPLOYER_NAME,
	MC.BARG_UNIT_ID,
	BARG_UNIT_NAME,
	MC.BILLING_ID,
	BILLING_ENTITY_NAME,
	BE.WORK_LOCATION_ID,
	WORK_LOCATION_NAME,
	START_DATE,
	STOP_DATE,
	CATEGORY_NAME JOB_CATEGORY,
	JOB_DESCRIPTION
FROM DBO.MEMBER_CONTRACT MC
INNER JOIN DBO.MEMBER M
	ON MC.MEMBER_ID=M.MEMBER_ID
INNER JOIN DBO.PERSON P
	ON M.PERSON_ID=M.PERSON_ID
INNER JOIN DBO.EMPLOYER EMP
	ON MC.EMPLOYER_ID=EMP.EMPLOYER_ID
INNER JOIN DBO.BARG_UNIT BU
	ON MC.BARG_UNIT_ID=BU.BARG_UNIT_ID
INNER JOIN DBO.BILLING_ENTITY BE
	ON MC.BILLING_ID=BE.BILLING_ID
INNER JOIN DBO.WORK_LOCATION W
	ON BE.WORK_LOCATION_ID=W.WORK_LOCATION_ID
INNER JOIN DBO.JOB_CLASS JC
	ON MC.JOB_CLASS_ID=JC.JOB_CLASS
INNER JOIN DBO.JOB_CATEGORY JCA
	ON MC.JOB_CATEGORY=JCA.JOB_CATEGORY
WHERE M.PERSON_ID=@PERSON_ID