CREATE TABLE [dbo].[MEMBER_JOB]
(
	[MEMBER_JOB_ID] BIGINT NOT NULL PRIMARY KEY, 
	[MEMBER_ID] NUMERIC(10) NOT NULL,
	[EMPLOYER_ID] NUMERIC (10) NOT NULL, 
    [START_DATE] DATETIME2 NULL, 
    [END_DATE] DATETIME2 NULL,
	[DATA_SOURCE] VARCHAR(100) NULL,
	[DATA_SOURCE_ID] VARCHAR(100) NULL,
    [INSERTED_BY] VARCHAR(100) NULL, 
    [INSERTED_DATE] DATETIME2 NULL DEFAULT GETDATE(), 
    [UPDATED_BY] VARCHAR(100) NULL, 
    [UPDATED_DATE] DATETIME2 NULL DEFAULT GETDATE(),
	CONSTRAINT [FK__MEMBER_JOBS__MEMBER] FOREIGN KEY ([MEMBER_ID]) REFERENCES [MEMBER]([MEMBER_ID]),
	CONSTRAINT [FK__MEMBER_JOBS__EMPLOYER] FOREIGN KEY ([EMPLOYER_ID]) REFERENCES [EMPLOYER]([EMPLOYER_ID])

)
