CREATE TABLE [dbo].[MEMBER_PROFILE]
(
	[MEMBER_PROFILE_ID] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
	[MEMBER_ID] NUMERIC(10) NOT NULL,
    [INITIATION_DATE] DATETIME2 NULL, 
    [JOIN_DATE] DATETIME2 NULL, 
    [FIELD_REP_ID] BIGINT NULL, 
    [FIELD_REP_NAME] VARCHAR(200) NULL, 
    [FIELD_REP_CONTACT_1] VARCHAR(200) NULL, 
    [FIELD_REP_CONTACT_2] VARCHAR(200) NULL,
	[DATA_SOURCE] VARCHAR(100) NULL,
	[DATA_SOURCE_ID] VARCHAR(100) NULL,
    [INSERTED_BY] VARCHAR(100) NULL, 
    [INSERTED_DATE] DATETIME2 NULL DEFAULT GETDATE(), 
    [UPDATED_BY] VARCHAR(100) NULL, 
    [UPDATED_DATE] DATETIME2 NULL DEFAULT GETDATE(), 
    CONSTRAINT [FK__MEMBER_PROFILE__MEMBER] FOREIGN KEY ([MEMBER_ID]) REFERENCES [MEMBER]([MEMBER_ID])
)
