CREATE TABLE [dbo].[MEMBER] (
    [MEMBER_ID]          NUMERIC (10)  NOT NULL,
    [PERSON_ID]          NUMERIC (10)  NOT NULL,
    [ELIG_ACTIVITY_DATE] DATETIME2 (7) NULL,
    [FREEZE_WORK]        CHAR (1)      NOT NULL,
    [INSERTED_BY]        VARCHAR (50)  NOT NULL,
    [INSERTED_DATE]      DATETIME2 (7) NOT NULL,
    [UPDATED_BY]         VARCHAR (50)  NULL,
    [UPDATED_DATE]       DATETIME2 (7) NULL,
    [IMPORT_DATE]        DATETIME      NOT NULL,
    CONSTRAINT [PK_MEMBER] PRIMARY KEY CLUSTERED ([MEMBER_ID] ASC),
    CONSTRAINT [FK_MEMBER_PERSON_ID] FOREIGN KEY ([PERSON_ID]) REFERENCES [dbo].[PERSON] ([PERSON_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[MEMBER] NOCHECK CONSTRAINT [FK_MEMBER_PERSON_ID];

