CREATE VIEW [dbo].[UVW_MEMBER_ADDRESS]
AS


	SELECT  
	    a.ADDRESS_ID,
		m.MEMBER_ID,
		m.PERSON_ID,
		a.ADDRESS_SOURCE,
		a.ADDRESS_TYPE,
		a.ADDRESS_1,
		a.ADDRESS_2,
		a.ADDRESS_3,
		a.CITY,
		a.COUNTRY,
		a.COUNTY,
		a.LATITUDE,
		a.LONGITUDE,
		a.POSTAL_CODE,
		a.[STATE],
		a.ZIP,
		a.START_DATE,
		a.STOP_DATE,
		a.INSERTED_DATE,
		a.UPDATED_DATE
	FROM dbo.ADDRESSES a
	JOIN dbo.MEMBER m ON a.KEY_VALUE = m.PERSON_ID
	--JOIN dbo.PERSON p ON a.KEY_VALUE = p.PERSON_ID 
	WHERE a.ENTITY_ID = 254
				AND
			GETDATE() BETWEEN ISNULL(a.START_DATE, '1900-01-01') AND ISNULL(a.STOP_DATE, '12/31/2999')



