CREATE VIEW [dbo].[UVW_MEMBER_JOBS]
	AS 
SELECT DISTINCT
	MC.MEMBER_CONTRACT_ID [MEMBER_JOB_UID],
	M.PERSON_ID,
	M.MEMBER_ID,
	MC.EMPLOYER_ID,
	EMP.EMPLOYER_NAME,
	MC.BARG_UNIT_ID,
	BU.BARG_UNIT_NAME,
	MC.BILLING_ID,
	BE.BILLING_ENTITY_NAME,
	BE.WORK_LOCATION_ID,
	W.WORK_LOCATION_NAME,
	CASE MC.MEMBER_CONTRACT_STATUS WHEN 'A' THEN 'Active' WHEN 'O' THEN 'On Leave' WHEN 'T' THEN 'Terminated' ELSE MEMBER_CONTRACT_STATUS END AS CONTRACT_STATUS,
	MC.START_DATE,
	MC.STOP_DATE,
	JCA.CATEGORY_NAME JOB_CATEGORY,
	JC.JOB_DESCRIPTION
	
FROM DBO.MEMBER_CONTRACT MC
INNER JOIN readonly.MEMBER M
	ON MC.MEMBER_ID=M.MEMBER_ID
INNER JOIN readonly.PERSON P
	ON P.PERSON_ID=M.PERSON_ID
INNER JOIN DBO.EMPLOYER EMP
	ON MC.EMPLOYER_ID=EMP.EMPLOYER_ID
INNER JOIN DBO.BARG_UNIT BU
	ON MC.BARG_UNIT_ID=BU.BARG_UNIT_ID
INNER JOIN DBO.BILLING_ENTITY BE
	ON MC.BILLING_ID=BE.BILLING_ID
INNER JOIN DBO.WORK_LOCATION W
	ON BE.WORK_LOCATION_ID=W.WORK_LOCATION_ID
INNER JOIN DBO.JOB_CLASS JC
	ON MC.JOB_CLASS_ID=JC.JOB_CLASS
INNER JOIN DBO.JOB_CATEGORY JCA
	ON MC.JOB_CATEGORY=JCA.JOB_CATEGORY
	where GETDATE() BETWEEN ISNULL(START_DATE, '2999-12-31') AND ISNULL(STOP_DATE, '2999-12-31') AND MC.MEMBER_CONTRACT_STATUS = 'A'
