CREATE TABLE [dbo].[ATTRIBUTE_VALUE] (
    [ATTRIBUTE_VALUE_ID] NUMERIC (10)  NOT NULL,
    [ATTRIBUTE_ID]       NUMERIC (10)  NOT NULL,
    [DESCRIPTION]        VARCHAR (250) NOT NULL,
    [INTERNAL_VALUE]     VARCHAR (2)   NOT NULL,
    [SEQ_NO]             NUMERIC (5)   NOT NULL,
    [USER_VALUE]         VARCHAR (2)   NOT NULL,
    CONSTRAINT [PK_ATTRIBUTE_VALUE] PRIMARY KEY CLUSTERED ([ATTRIBUTE_VALUE_ID] ASC),
    CONSTRAINT [FK_ATTRIBUTE_VALUE_ATTRIBUTE_ID] FOREIGN KEY ([ATTRIBUTE_ID]) REFERENCES [dbo].[ATTRIBUTE] ([ATTRIBUTE_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[ATTRIBUTE_VALUE] NOCHECK CONSTRAINT [FK_ATTRIBUTE_VALUE_ATTRIBUTE_ID];

