CREATE TABLE [dbo].[ATTRIBUTE] (
    [ATTRIBUTE_ID]    NUMERIC (10) NOT NULL,
    [ATTRIBUTE_CLASS] VARCHAR (2)  NOT NULL,
    [ATTRIBUTE_NAME]  VARCHAR (50) NULL,
    [ATTRIBUTE_TYPE]  VARCHAR (2)  NOT NULL,
    CONSTRAINT [PK_ATTRIBUTE] PRIMARY KEY CLUSTERED ([ATTRIBUTE_ID] ASC)
);

