CREATE TABLE [dbo].[CONTRACT](
	[CONTRACT_ID] [numeric](10, 0) NOT NULL,
	[BARG_UNIT_ID] [numeric](10, 0) NOT NULL,
	[ACTUAL_START_DATE] [datetime2](7) NULL,
	[ACTUAL_STOP_DATE] [datetime2](7) NULL,
	[CONTRACT_START_DATE] [datetime2](7) NOT NULL,
	[CONTRACT_STOP_DATE] [datetime2](7) NULL,
 CONSTRAINT [PK_CONTRACT] PRIMARY KEY CLUSTERED 
(
	[CONTRACT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CONTRACT]  WITH NOCHECK ADD  CONSTRAINT [FK_CONTRACT_BARG_UNIT_ID] FOREIGN KEY([BARG_UNIT_ID])
REFERENCES [dbo].[BARG_UNIT] ([BARG_UNIT_ID])
GO

ALTER TABLE [dbo].[CONTRACT] NOCHECK CONSTRAINT [FK_CONTRACT_BARG_UNIT_ID]