CREATE TABLE [dbo].[CONTACT_INFO_SUBTYPE] (
    [CONTACT_INFO_SUBTYPE_ID] NUMERIC (10) NOT NULL,
    [INTERNAL_NAME]           VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CONTACT_INFO_SUBTYPE] PRIMARY KEY CLUSTERED ([CONTACT_INFO_SUBTYPE_ID] ASC)
);

