CREATE TABLE [dbo].[COUNTRY] (
    [COUNTRY_ID]   NUMERIC (10) NOT NULL,
    [COUNTRY_CODE] VARCHAR (10) NOT NULL,
    [COUNTRY_NAME] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_COUNTRY] PRIMARY KEY CLUSTERED ([COUNTRY_ID] ASC)
);

