CREATE TABLE [dbo].[CRMMESSAGERESPONSE]
(
	[ID] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
    [SOURCE] NCHAR(16) NULL, 
    [REQUEST_NAME] NCHAR(16) NULL, 
    [DATA] TEXT NULL, 
    [DATA_ID] NCHAR(16) NULL, 
    [DATA_TYPE] NCHAR(150) NULL, 
    [CREATED_AT] DATETIME2 NULL, 
    [MESSAGE_ID] BIGINT NULL, 
    [RESPONSE_CODE] NCHAR(16) NULL,
	CONSTRAINT [FK_CRMMESSAGERESPONSE_CRMMESSAGEREQUEST_ID] FOREIGN KEY ([MESSAGE_ID]) REFERENCES [dbo].CRMMESSAGEREQUEST ([ID])
)
