CREATE TABLE [dbo].[CRMMESSAGEREQUEST]
(
	[ID] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
    [SOURCE] NCHAR(16) NOT NULL, 
    [REQUEST_NAME] NCHAR(16) NOT NULL, 
    [DATA] TEXT NULL, 
    [DATA_ID] NCHAR(16) NULL, 
    [DATA_TYPE] NCHAR(150) NULL, 
    [CREATED_AT] DATETIME2 NOT NULL, 
    [SERVICE_NAME] NCHAR(50) NOT NULL
)
