CREATE TABLE [dbo].[DATASHEET_DEFINITION] (
    [DATASHEET_ID]              NUMERIC (10)   NOT NULL,
    [DS_NAME]                   VARCHAR (50)   NOT NULL,
    [DISPLAY_NAME]              VARCHAR (50)   NOT NULL,
    [CUSTOM_SQL]                VARCHAR (2000) NULL,
    [DATAWINDOW_SYNTAX]         TEXT           NULL,
    [ACTIVE]                    CHAR (1)       NOT NULL,
    [DATA_STYLE]                CHAR (1)       NOT NULL,
    [INSTANCE_FLAG]             CHAR (1)       NOT NULL,
    [SEQ_NO]                    NUMERIC (10)   NOT NULL,
    [ENTITY_ID]                 NUMERIC (10)   NOT NULL,
    [KEY_VALUE]                 NUMERIC (10)   NOT NULL,
    [PROMPT_FOR_ADD]            VARCHAR (50)   NULL,
    [USER_DEFINED_PRESENTATION] CHAR (1)       NOT NULL,
    [QUERY_VISIBLE]             CHAR (1)       NOT NULL,
    [QUERY_VIEW_NAME]           VARCHAR (50)   NULL,
    [INSERTED_BY]               VARCHAR (50)   NOT NULL,
    [INSERTED_DATE]             DATETIME2 (7)  NOT NULL,
    [UPDATED_BY]                VARCHAR (50)   NULL,
    [UPDATED_DATE]              DATETIME2 (7)  NULL,
    [TAB_ORDER_OPTION]          VARCHAR (2)    NOT NULL,
    [SHOW_COMMENT]              CHAR (1)       NOT NULL,
    [PROMPT_TYPE]               VARCHAR (2)    NULL,
    [DATASHEET_GROUP_ID]        NUMERIC (10)   NULL,
    [RETRIEVE_ON_DEMAND]        CHAR (1)       NOT NULL,
    [SCALE]                     NUMERIC (10)   NULL,
    [SOURCE_RULE_ID]            NUMERIC (10)   NULL,
    [VALIDATION_RULE_ID]        NUMERIC (10)   NULL,
    [PERSISTENCE_RULE_ID]       NUMERIC (10)   NULL,
    [PRODUCT_FLAG]              CHAR (1)       NOT NULL,
    [ADD_ROW_FLAG]              CHAR (1)       NOT NULL,
    [DELETE_ROW_FLAG]           CHAR (1)       NOT NULL,
    [EDITABLE_ROW_RULE_ID]      NUMERIC (10)   NULL,
    [DISPLAY_RULE_ID]           NUMERIC (10)   NULL,
    [TOOLBAR_ID]                NUMERIC (10)   NULL,
    [SHOW_HELP_FLAG]            VARCHAR (1)    NOT NULL,
    [PROMPT_SORT_TYPE]          VARCHAR (2)    NULL,
    [STORAGE_ENTITY_ID]         NUMERIC (10)   NOT NULL,
    [MIGRATION_FLAG]            VARCHAR (1)    NOT NULL,
    [HORIZONTAL_COLUMNS]        NUMERIC (5)    NOT NULL,
    [EDITABLE_RULE_ID]          NUMERIC (10)   NULL,
    [PARENT_DATASHEET_ID]       NUMERIC (10)   NULL,
    CONSTRAINT [PK_DATASHEET_DEFINITION] PRIMARY KEY CLUSTERED ([DATASHEET_ID] ASC)
);

