CREATE TABLE [dbo].[ENTITY_ATTRIBUTE] (
    [ENTITY_ID]                NUMERIC (10)   NOT NULL,
    [ATTRIBUTE_ID]             NUMERIC (10)   NOT NULL,
    [PRIMARY_KEY]              CHAR (1)       NOT NULL,
    [BYPASS_DERIVED]           CHAR (1)       NOT NULL,
    [HISTORY]                  CHAR (1)       NOT NULL,
    [CUSTOM]                   CHAR (1)       NOT NULL,
    [CARDINALITY]              NUMERIC (5)    NULL,
    [LINK_NO]                  NUMERIC (5)    NULL,
    [NOTES]                    VARCHAR (250)  NULL,
    [DERIVED_FORMULA]          VARCHAR (4000) NULL,
    [INSERTED_BY]              VARCHAR (50)   NOT NULL,
    [INSERTED_DATE]            DATETIME2 (7)  NOT NULL,
    [UPDATED_BY]               VARCHAR (50)   NULL,
    [UPDATED_DATE]             DATETIME2 (7)  NULL,
    [QUERY_VISIBLE]            CHAR (1)       NOT NULL,
    [DISPLAY_NAME]             VARCHAR (50)   NULL,
    [QUERY_DISPLAY_NAME]       VARCHAR (50)   NULL,
    [HISTORY_REVIEW_REQUIRED]  CHAR (1)       NOT NULL,
    [VISIBLE_FLAG]             CHAR (1)       NOT NULL,
    [SEQ_NO]                   NUMERIC (5)    NULL,
    [ENTITY_ATTRIBUTE_ID]      NUMERIC (10)   NOT NULL,
    [ALTERNATE_KEY_FLAG]       CHAR (1)       NULL,
    [VALUE_BUSINESS_RULE_ID]   NUMERIC (10)   NULL,
    [DEFAULT_VALUE]            VARCHAR (50)   NULL,
    [REQUIRED_FLAG]            CHAR (1)       NOT NULL,
    [NOWRAP_FLAG]              CHAR (1)       NOT NULL,
    [SECURED_FIELD_FLAG]       CHAR (1)       NOT NULL,
    [LOG_CHANGE_FOR_ELIG_CALC] VARCHAR (1)    NOT NULL,
    [IMPORT_DATE]              DATETIME       NOT NULL,
    CONSTRAINT [PK_ENTITY_ATTRIBUTE] PRIMARY KEY CLUSTERED ([ENTITY_ATTRIBUTE_ID] ASC),
    --CONSTRAINT [FK_ENTITY_ATTRIBUTE_ATTRIBUTE_ID] FOREIGN KEY ([ATTRIBUTE_ID]) REFERENCES [dbo].[ATTRIBUTE] ([ATTRIBUTE_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_ENTITY_ATTRIBUTE_ENTITY_ID] FOREIGN KEY ([ENTITY_ID]) REFERENCES [dbo].[ENTITY] ([ENTITY_ID]) NOT FOR REPLICATION
);


--GO
--ALTER TABLE [dbo].[ENTITY_ATTRIBUTE] NOCHECK CONSTRAINT [FK_ENTITY_ATTRIBUTE_ATTRIBUTE_ID];


--GO
--ALTER TABLE [dbo].[ENTITY_ATTRIBUTE] NOCHECK CONSTRAINT [FK_ENTITY_ATTRIBUTE_ENTITY_ID];

