CREATE TABLE [dbo].[ENTITY_ALIAS] (
    [ENTITY_ALIAS_ID] NUMERIC (10)  NOT NULL,
    [ENTITY_ID]       NUMERIC (10)  NOT NULL,
    [KEY_VALUE]       NUMERIC (10)  NOT NULL,
    [NAME_1]          VARCHAR (250) NULL,
    CONSTRAINT [PK_ENTITY_ALIAS] PRIMARY KEY CLUSTERED ([ENTITY_ALIAS_ID] ASC),
    CONSTRAINT [FK_ENTITY_ALIAS_ENTITY_ID] FOREIGN KEY ([ENTITY_ID]) REFERENCES [dbo].[ENTITY] ([ENTITY_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[ENTITY_ALIAS] NOCHECK CONSTRAINT [FK_ENTITY_ALIAS_ENTITY_ID];

