CREATE TABLE [dbo].[JOB_CATEGORY] (
    [JOB_CATEGORY_ID] NUMERIC (10) NOT NULL,
    [JOB_CATEGORY]    VARCHAR (25) NOT NULL,
    [CATEGORY_NAME]   VARCHAR (50) NULL,
    CONSTRAINT [PK_JOB_CATEGORY] PRIMARY KEY CLUSTERED ([JOB_CATEGORY_ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_JOB_CATEGORY]
    ON [dbo].[JOB_CATEGORY]([JOB_CATEGORY] ASC);

