CREATE TABLE [dbo].[MEMBER_CONTRACT] (
    [BILLING_ID]                NUMERIC (10)    NULL,
    [EMPLOYER_ID]               NUMERIC (10)    NOT NULL,
    [BARG_UNIT_ID]              NUMERIC (10)    NULL,
    [CERTIFIED_LEAVE_STOP_DATE] DATETIME2 (7)   NULL,
    [DATE_01]                   DATETIME2 (7)   NULL,
    [DATE_02]                   DATETIME2 (7)   NULL,
    [DATE_03]                   DATETIME2 (7)   NULL,
    [DATE_04]                   DATETIME2 (7)   NULL,
    [DATE_08]                   DATETIME2 (7)   NULL,
    [INSERTED_DATE]             DATETIME2 (7)   NOT NULL,
    [JOB_CATEGORY]              VARCHAR (25)    NULL,
    [JOB_CLASS_ID]              VARCHAR (10)    NULL,
    [MEMBER_CONTRACT_CODE_01]   VARCHAR (100)   NULL,
    [MEMBER_CONTRACT_FLAG_02]   CHAR (1)        NULL,
    [MEMBER_CONTRACT_FLAG_15]   CHAR (1)        NULL,
    [MEMBER_CONTRACT_FLAG_18]   CHAR (1)        NULL,
    [MEMBER_CONTRACT_ID]        NUMERIC (10)    NOT NULL,
    [MEMBER_CONTRACT_STATUS]    VARCHAR (2)     NOT NULL,
    [MEMBER_CONTRACT_TYPE]      VARCHAR (2)     NULL,
    [MEMBER_ID]                 NUMERIC (10)    NOT NULL,
    [START_DATE]                DATETIME2 (7)   NULL,
    [STOP_DATE]                 DATETIME2 (7)   NULL,
    [UNIT_01]                   NUMERIC (13, 4) NULL,
    [UPDATED_DATE]              DATETIME2 (7)   NULL,
    [VOTING_STATUS]             VARCHAR (2)     NULL,
    [UPDATED_BY]                VARCHAR (50)    NULL,
    [INSERTED_BY]               VARCHAR (50)    NOT NULL,
    [IMPORT_DATE]               DATETIME        NOT NULL,
    CONSTRAINT [PK_MEMBER_CONTRACT] PRIMARY KEY CLUSTERED ([MEMBER_CONTRACT_ID] ASC),
    --CONSTRAINT [FK_MEMBER_CONTRACT_BARG_UNIT_ID] FOREIGN KEY ([BARG_UNIT_ID]) REFERENCES [dbo].[BARG_UNIT] ([BARG_UNIT_ID]) NOT FOR REPLICATION,
    --CONSTRAINT [FK_MEMBER_CONTRACT_BILLING_ID] FOREIGN KEY ([BILLING_ID]) REFERENCES [dbo].[BILLING_ENTITY] ([BILLING_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_MEMBER_CONTRACT_EMPLOYER_ID] FOREIGN KEY ([EMPLOYER_ID]) REFERENCES [dbo].[EMPLOYER] ([EMPLOYER_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_MEMBER_CONTRACT_JOB_CATEGORY] FOREIGN KEY ([JOB_CATEGORY]) REFERENCES [dbo].[JOB_CATEGORY] ([JOB_CATEGORY]) NOT FOR REPLICATION
);


--GO
--ALTER TABLE [dbo].[MEMBER_CONTRACT] NOCHECK CONSTRAINT [FK_MEMBER_CONTRACT_BARG_UNIT_ID];


--GO
--ALTER TABLE [dbo].[MEMBER_CONTRACT] NOCHECK CONSTRAINT [FK_MEMBER_CONTRACT_BILLING_ID];


GO
ALTER TABLE [dbo].[MEMBER_CONTRACT] NOCHECK CONSTRAINT [FK_MEMBER_CONTRACT_EMPLOYER_ID];


GO
ALTER TABLE [dbo].[MEMBER_CONTRACT] NOCHECK CONSTRAINT [FK_MEMBER_CONTRACT_JOB_CATEGORY];


GO
CREATE NONCLUSTERED INDEX [UNiQUE_IND]
    ON [dbo].[MEMBER_CONTRACT]([MEMBER_CONTRACT_ID] ASC);

