CREATE TABLE [dbo].[STATE] (
    [STATE_ID]   NUMERIC (10) NOT NULL,
    [STATE_CODE] VARCHAR (10) NOT NULL,
    [STATE_NAME] VARCHAR (50) NOT NULL,
    [COUNTRY_ID] NUMERIC (10) NOT NULL,
    CONSTRAINT [PK_STATE] PRIMARY KEY CLUSTERED ([STATE_ID] ASC),
    CONSTRAINT [FK_STATE_COUNTRY_ID] FOREIGN KEY ([COUNTRY_ID]) REFERENCES [dbo].[COUNTRY] ([COUNTRY_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[STATE] NOCHECK CONSTRAINT [FK_STATE_COUNTRY_ID];

