CREATE TABLE [dbo].[TD_ProviderAddress](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AddressId] [int] NOT NULL,
	[ProviderId] [int] NOT NULL,
	[Phone1] [varchar](25) NULL,
	[Phone2] [varchar](25) NULL,
	[Group1] [varchar](90) NULL,
	[Group2] [varchar](90) NULL,
	[Group3] [varchar](90) NULL,
	[Group4] [varchar](90) NULL,
	[Group5] [varchar](90) NULL,
	[Group6] [varchar](90) NULL,
	[Group7] [varchar](90) NULL,
	[SunOpen] [varchar](4) NULL,
	[SunClose] [varchar](4) NULL,
	[MonOpen] [varchar](4) NULL,
	[MonClose] [varchar](4) NULL,
	[TuesOpen] [varchar](4) NULL,
	[TuesClose] [varchar](4) NULL,
	[WedOpen] [varchar](4) NULL,
	[WedClose] [varchar](4) NULL,
	[ThuOpen] [varchar](4) NULL,
	[ThuClose] [varchar](4) NULL,
	[FriOpen] [varchar](4) NULL,
	[FriClose] [varchar](4) NULL,
	[SatOpen] [varchar](4) NULL,
	[SatClose] [varchar](4) NULL,
	[IsAfterHours] [bit] NULL,
	[IsAcceptNew] [bit] NULL,
	[ProviderRoleId] [int] NOT NULL,
	[NetworkId] [int] NULL,
	[ProviderTaxId] [varchar](9) NULL,
	[ProviderWebsite] [varchar](100) NULL,
	[InPatient] [varchar](1) NULL,
	[OutPatient] [varchar](1) NULL,
	[IsPreferred] [varchar](1) NULL,
	[ClassCode] [varchar](3) NULL,
	[EffDate] [datetime] NULL,
	[EndDate] [datetime] NULL,
	[MHNeffDate] [varchar](8) NULL,
	[MHNendDate] [varchar](8) NULL,
	[PPOeffDate] [varchar](8) NULL,
	[PPOendDate] [varchar](8) NULL,
	[HMOeffDate] [varchar](8) NULL,
	[HMOendDate] [varchar](8) NULL,
	[BPPPOeffDate] [varchar](8) NULL,
	[BPPPOendDate] [varchar](8) NULL,
	[BPHMOeffDate] [varchar](8) NULL,
	[BPHMOendDate] [varchar](8) NULL,
	[POSeffDate] [varchar](8) NULL,
	[POSendDate] [varchar](8) NULL,
	[PrefeffDate] [varchar](8) NULL,
	[PrefendDate] [varchar](8) NULL,
	[HospitalAff] [varchar](800) NULL,
	[PhotoURI] [varchar](1000) NULL,
	[HospitalEmp] [varchar](20) NULL,
	[BusinessLogo] [varchar](1000) NULL,
	[PhotoURIAzure] [varchar](1000) NULL,
	[ProviderScore] [int] NULL,
 CONSTRAINT [PK_ProviderAddressId] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]